CREATE TABLE Todos (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  task TEXT,
  completed BOOLEAN DEFAULT FALSE,
  due_date DATE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP
);
