version: '3'

services:
  db:
    image: postgres
    restart: always
    container_name: postgresdb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: todos
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
