// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
)

type Todo struct {
	ID        int32
	ParentID  sql.NullInt32
	Task      string
	Completed sql.NullBool
	DueDate   sql.NullTime
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}
